volumes:
  compose-volume:
    external: true
    name: postgres-volume

services:
  app:
    image: github-action-khonhai
    build:
      context: ..
    environment:
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://postgres:academy@postgres:5432/postgres?schema=public
      AWS_BUCKET_NAME: khonhai-bucket
      AWS_BUCKET_REGION: ap-southeast-1
      AWS_ACCESS_KEY: AKIAYXEDKVHLOVTISAFL
      AWS_SECRET_ACCESS_KEY: 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
      CORS: "no"
    ports:
      - "8000:8000"
    
  redis:
    image: redis:latest

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=academy
    volumes:
      - "compose-volume:/var/lib/postgresql"
