services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: gigi
      MONGO_INITDB_ROOT_PASSWORD: taichi

  app:
    # Build image nodeserver from Dockerfile in GitHub repo
    image: nodejs-cicd
    build:
      # context: https://github.com/CleverseAcademy/nodejs-cicd.git#develop
      context: ..
    environment:
      MONGODB_USERNAME: gigi
      MONGODB_PASSWORD: taichi
      MONGODB_HOST: mongodb
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://pguser:pgpassword@postgres:5432
    ports:
      - "8000:8000"

  redis:
    image: redis:7.0

  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
