# services:
#   mongodb:
#     image: mongo
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: gigi
#       MONGO_INITDB_ROOT_PASSWORD: taichi

  app:
    # Build image nodeserver from Dockerfile in GitHub repo
    image: github-action-khonhai
    build:
      # context: https://github.com/CleverseAcademy/nodejs-cicd.git#develop
      context: ..
    environment:
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://postgres:academy@localhost:5432/project?schema=public
    ports:
      - "8000:8000"

  redis:
    image: redis:7.0

  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=academy
